### ISSUE TITLE
你好，打扰了，我想问一个有关于migrate的问题

### ISSUE THREAD

**Issue by seven-share** [kosmosr/fisher#1]
需要迁移的数据库模型一定要放在manage.py里引入吗？感觉这样很多余，不知道为什么？求解

**Comment by kosmosr** [comment]
有的时候migrate检测不到你修改了模型 就需要手动导入 如果没出现问题 可以不用

**Comment by seven-share** [comment]
我这两天仔细查了这个问题，自己也做了总结，分享给你，如果你感兴趣，可以看看，如果有什么不对的，欢迎指正，https://github.com/seven-share/flaskMigrateTry
